### ISSUE TITLE
Leaflet layers legend button icon missing

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-rem-v3#13]
Looks like: <img width="107" alt="screen shot 2017-01-14 at 10 47 17 pm" src="https://cloud.githubusercontent.com/assets/944642/21960092/70bb8468-daab-11e6-9538-57b17faf2ff5.png">
Should look like <img width="96" alt="screen shot 2017-01-14 at 10 47 22 pm" src="https://cloud.githubusercontent.com/assets/944642/21960093/720b4c0e-daab-11e6-8981-557630495670.png">

`vendor-bundle.js:38880 GET https://rem-dev.petabencana.id/images/layers-2x.png 403 ()`

**Comment by matthewberryman** [comment]
Images weren't being deployed by jenkins for prod or dev as the build script hadn't been updated when the /images/ folder was put in (the build script was originally copied from petabencana.id which has images under another path). Additionally, the new rem-dev cloudfront distribution wasn't quite set up for aurelia, so was returning a 403 (whereas rem was returning 200 but then no content)
