### ISSUE TITLE
prompted twice or more for auth0 login

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-rem-v3#15]
Sometimes this happens, sometimes not.

**Comment by matthewberryman** [comment]
seeing this across browsers (Chrome beta + latest stable Firefox)

**Comment by tomasholderness** [comment]
Hi @matthewberryman do you have to physically click the login button twice? Not wanting to sound pedantic but just trying to make sure I can recreate at this end. Thanks

**Comment by matthewberryman** [comment]
@talltom sorry for delay (busy demoing petabencana to students as part of IoT session, including some test tweets :)

Yes just to confirm I have to click the button twice (or more), although the second time it has my credential saved so I don't need to log in again. Just a though that it may be my ad blocker interfering. Hang on a sec I will test.

**Comment by matthewberryman** [comment]
Nope, it's not the ad blocker. I get this in incognito mode in Chrome (with ad blocker not enabled in incognito mode).

**Comment by cgjerow** [comment]
Hi @matthewberryman Were you able to resolve your issue? I am consistently directed to login an extra time.

**Comment by matthewberryman** [comment]
@cgjerow Much less often than it used to. Just checked then on the latest Chrome and Firefox and all good. I suspect this is a cookie issue with auth0 itself. @talltom did you / the team in Boston figure out the cause?

**Comment by tomasholderness** [comment]
@matthewberryman, I think the cookie issue is probably causing @cgjerow issue. I think, the general problem is that we're calling an Auth0 API and if the reply is slow generating a race condition on the page where the authentication hasn't been returned quick enough. My guess is that this is also the reason why the problem isn't repeatable consistently.
