### ISSUE TITLE
REM Time Difference to Map 

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/cognicity-rem-v3#32]
FY17Ext Dev Meeting Field Office 12 _ request to correct bug that shows a 7 hour difference between the real report time and its display in the REM.

See detailed description:
https://github.com/urbanriskmap/petabencana.id/issues/221#issuecomment-324738987

**Comment by tomasholderness** [comment]
7 hour offset probably due to time zone bug. (ICT is UTC+0700)

**Comment by tomasholderness** [comment]
This was fixed in a13bdc04ea83540c842aae4ffda4773be4c0d382
- reports table was not using the `formatTime` function required to put times into ICT.
