### ISSUE TITLE
Analytics, Reporting and Time series functionality for REM

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-rem-v3#33]

**Comment by ojha-url** [comment]
- Top: Graph of flooded areas & reports (count) filtered by time series
- Middle: Map with flooded area polygons (color coded by highest flood alert issued in selected time period) + reports (dots)
- Check box to toggle report icons, stat for reports count
- Bottom: Slider to select time period, start (-7d) & end (now)

**Comment by ojha-url** [comment]
Repository:
https://github.com/urbanriskmap/cognicity-analytics

Staged here:
https://dashboard-dev.petabencana.id
